pages/urls.py
from django.urls import path
from .import views_bic_part
from .import views_lire
from .import views_bic

avaliable= 'views_bic'
print('Running:',avaliable)

if avaliable == 'views_bic':

	urlpatterns = [
	    path('index/', views_bic.home, name='index'),
	    path('search/', views_bic.autocomplete, name='search'),
	]

if avaliable == 'views_bic_part':

	urlpatterns = [
	    path('index/', views_bic_part.home, name='index'),
	    path('search/', views_bic_part.autocomplete, name='search'),
	]

if avaliable == 'views_lire':

	urlpatterns = [
	    path('index/', views_lire.home, name='index'),
	    path('search/', views_lire.autocomplete, name='search'),
	]

sri/urls.py
from django.contrib import admin
from django.urls import path, include
#
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sri/', include('pages.urls')),
    path('search/', include('haystack.urls'))
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models

# python3 manage.py makemigrations (cria a tabela)
# python3 manage.py migrate (aplica a tabela ao banco)
# pip install Pillow

class SearchManager(models.Manager):
	#from pages.models import BaseImage
	#BaseImage.objects.search('colher')
	def search(self, query):
		return self.get_queryset().filter(models.Q(search_image__icontains=query))

class BaseImage(models.Model):
	#campo de pesquisa por imagem (path da imagem)
	search_image= models.ImageField(upload_to='tmp', verbose_name='path_imagem', null=True, blank=True)
	#campo de pesquisa por texto
	search_text= models.TextField('search_text', null=True, blank=True)
	#campo para o vetor de caracteristicas da imagem BIC
	descriptorBIC= models.TextField('descriptorBIC', null=True, blank=True)
	#campo para o vetor de caracteristicas da imagem BIC part
	descriptorBIC_part= models.TextField('descriptorBIC_part', null=True, blank=True)
	#objeto para consulta personalizada
	objects= SearchManager()

	def __str__(self):
		return self.search_text

	#def get_absolute_url(self):
	#	return reverse("resultQueryText:detail", kwargs={"slug": self.slug})

	class Meta:
		verbose_name= 'SearchImagem'
		verbose_name_plural = 'BaseImage'
		ordering = ['search_image']

pages/forms.py
from django import forms

# from pages.forms import FormBaseImage
# form= FormBaseImage()
# print(form.as_p())

class FormBaseImage(forms.Form):
    search_text= forms.CharField(label='', max_length=150, required=False)
    search_image= forms.ImageField(label='', required=False)

pages/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>SRI-v.1</title>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    $( function() {
        $( "#id_search_text" ).autocomplete({
            minLength: 1,
            source: function(req, add){
                var search_text= $("#id_search_text").val();
                $.ajax({
                    url: '/sri/search/',
                    async: true,
                    data_type: 'json',
                    type: 'GET',
                    data: {'terms': search_text},
                    success: function(data){
                        console.log(JSON.parse(data));
                        add(JSON.parse(data))
                        document.getElementById("noneResult").style.display= "None";
                    },
                    error: function(err){
                        console.log('err: '+err);
                    }
                });
            }
        });
    });
  </script>
</head>
<body>
    <h1>Image Recovery System</h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="pure-control-group">
            {{ form }}
            <button class="pure-button">Search</button>
        </div>
    </form>

    {% if is_image %}
    <div id="noneResult">
    <label>Type: image</label>
    <fieldset>
        {% for q in resultQueryImage %}
            <ul style="float: left;">
                <li>{{ q.search_text }}</li>  
                {% if q.search_image %}
                    <img src="{{ q.search_image.url }}" alt="no image" width="100" height="75">
                {% endif %}    
            </ul>    
        {% endfor %}
    </fieldset>
    <label>Total images found: {{ total_query_images }}</label>
    </div>
    {% endif %}

    {% if is_text %}
    <div id="noneResult">
    <label>Type: text</label>
    <fieldset>
        {% for q in resultQueryText %}
            <ul style="float: left;">
                <li>{{ q.object.search_text }}</li>  
                {% if q.object.search_image %}
                    <img src="{{ q.object.search_image.url }}" alt="no image" width="100" height="75">
                {% endif %}
            </ul>    
        {% endfor %}
    </fieldset>
    <label>Total images found: {{ total_query_texts }}</label>
    </div>
    {% endif %}

    {% if is_text_image %}
    <div id="noneResult">
    <label>Type: text and image</label>
    <fieldset>
        {% for q in resultQueryTextImage %}
            <ul style="float: left;">
                <li>{{ q.search_text }}</li>  
                {% if q.search_image %}
                    <img src="{{ q.search_image.url }}" alt="no image" width="100" height="75">
                {% endif %}
            </ul>    
        {% endfor %}
    </fieldset>
    <label>Total images found: {{ total_query_text_image }}</label>
    </div>
    {% endif %}

    {% if noneResult %}
    <fieldset id="noneResult">
        <label><i>No results found. Enter a text or insert a picture.</i></label>
    </fieldset>
    {% endif %}
    
</body>
</html>

pages/templates/search/search.html
<!doctype html>
{% csrf_token %}
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Autocomplete</title>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#terms" ).autocomplete({
      minLength: 3,
      source: function(req, add){
        var search_text= $("#terms").val();
        $.ajax({
          url: '/sri/search/',
          async: true,
          data_type: 'json',
          type: 'GET',
          data: {'terms': search_text},
          success: function(data){
            console.log(JSON.parse(data));
            add(JSON.parse(data))
          },
          error: function(err){
            console.log('err: '+err);
          }
        });
      }
    });
  } );
  </script>
</head>
<body>
 
<div class="ui-widget">
  <label for="terms">terms: </label>
  <input id="terms">
</div>

</body>
</html>